#!/usr/bin/env python3

import logging
from mcr.libmcr import g5k, ApiError
import sys
from mcr.libsettings import *
import mcr.libsession
from mcr.libprint import print_items
import argparse

logging.basicConfig(stream=sys.stdout, level=logging.INFO)

import argparse


class ParseSettings(argparse.Action):

    def __init__(self, option_strings, dest, nargs=None, **kwargs):
        super(ParseSettings, self).__init__(option_strings, dest, **kwargs)

    def __call__(self, parser, namespace, value, option_string=None):
        k, v = value.split('=')
        namespace.settings[k] = v


arg_parser = argparse.ArgumentParser()
subparsers = arg_parser.add_subparsers(dest="command")
arg_parser.add_argument("-q", help="quiet mode, just display the uids", action="store_true", dest="quiet")
arg_parser.add_argument("--format", help="output formatting template, jinja", default=None)
arg_parser.add_argument("--dry-run", help="just print the http requests", action="store_true", dest="dry")
arg_parser.add_argument("--config",
                        help="path of the config file, by default mcc will look at a settings.yaml file in the current folder",
                        default="settings.yaml")
arg_parser.add_argument("-s", action=ParseSettings, help="override config file settings", nargs="*", default={},
                        dest="settings")

job_parser = subparsers.add_parser("job")

action_job_parser = job_parser.add_subparsers(dest="action")

list_job_parser = action_job_parser.add_parser("list")
list_job_parser.add_argument("uid", type=int, nargs='?', help='uid of the job to inspect', default=None)
list_job_parser.add_argument("--sites", type=str, nargs='*', help='list of sites for job search',
                             default=None)
list_job_parser.add_argument("--filter", type=str, nargs='*', help='list of filters to job seach, e.g. status=running',
                             default=[])

add_job_parser = action_job_parser.add_parser("add")
add_job_parser.add_argument("site", type=str, help='site where to deploy the job')
add_job_parser.add_argument("node_count", type=int, help='how many node to book')
add_job_parser.add_argument("duration_adv", type=str, help='how many node to book', choices=["until", 'for'],
                            default="for")
add_job_parser.add_argument("duration", type=str, help='duration or expiration date for the job', default="1h")

del_job_parser = action_job_parser.add_parser("del")
del_job_parser.add_argument("uid", type=str, help='uid of the job to delete')
del_job_parser.add_argument("--site", type=str, nargs='?', help='hint of where the site job is',
                            default=None)

dep_parser = subparsers.add_parser("dep")

action_dep_parser = dep_parser.add_subparsers(dest="action")

add_dep_parser = action_dep_parser.add_parser("add")
add_dep_parser.add_argument("uid", type=str, help='uid of the job on which to do the deployment')
add_dep_parser.add_argument("nodes", type=str, nargs='*',
                            help='names of the nodes on which to perform the deployement. all nodes from the job are deployed if ommited',
                            default=None)
add_dep_parser.add_argument("--site", type=str, nargs='?', help='hint of where the site job is',
                            default=None)
add_dep_parser.add_argument("--environment", type=str, help='name of the environment to install',
                            default="debian9-x64-base")

list_dep_parser = action_dep_parser.add_parser("list")
list_dep_parser.add_argument("uid", type=str, nargs='?', help='uid of the dep to inspect', default=None)
list_dep_parser.add_argument("--site", type=str, nargs='*', help='list of sites for dep search')
list_dep_parser.add_argument("--filter", type=str, nargs='*',
                             help='list of filters to dep seach, e.g. state=running state!=error',
                             default=[])

# Parse
opts = arg_parser.parse_args()

settings_api_url, settings_login, settings_pwd, settings_ssh_key_file_public \
    , settings_ssh_key_file_private, settings_g5k_alias, settings_environment \
    , settings_default_site, settings_ssh_key = load_settings(opts.config, opts.settings)

# default values

# can't have both -s default_site=... and --sites ...
if "default_site" in opts.settings and opts.__contains__("sites") and opts.sites is not None:
    print("Can't override both default site and possible sites")
    exit(1)

if opts.__contains__("site") and opts.site is None:
    opts.site = settings_default_site
if opts.__contains__("sites") and opts.sites is None:
    opts.sites = [settings_default_site]

# create API session

s = mcr.libsession.create_session(settings_api_url, settings_login, settings_pwd)


def get_link_href(entity, rel="self"):
    for item in entity["links"]:

        if item["rel"] == rel:
            return item["href"]
    return ""


def find_job(job, sites_hints):
    return find_sub_item("jobs", int(job), sites_hints)


def find_dep(dep, sites_hints):
    return find_sub_item("deployments", dep, sites_hints)


def print_site_item(items_name, uid, sites, filter):
    kwargs = {splat[0]: splat[1] for splat in (item.split("=") for item in filter)}
    kwargs["user_uid"] = settings_login

    if opts.uid is None:
        for site in g5k(s)("stable")("sites").get_items():
            if sites is None or site in sites:
                item = g5k(s)("stable")("sites")(site)(items_name).get_items_filtered(data=not opts.quiet, **kwargs)
                if len(item) > 0:
                    print_items(item, opts.format)
    else:

        print_items([g5k(s)(find_sub_item(items_name, uid, sites)).get_raw()], opts.format)
        exit(0)


def find_sub_item(item, uid, sites_hints):
    '''

    :param job: job uid
    :param sites_hints: list of possible sites to look for. If list is empty of None, all g5k sites are inspected
    :return: the url of the job
    '''

    if sites_hints is None or len(sites_hints) == 0:
        target_sites = g5k(s)("stable")("sites").get_items()
    else:
        target_sites = sites_hints

    for site in target_sites:
        try:
            items_for_site = g5k(s)("stable")("sites")(site)(item)(uid).get_raw()
            return get_link_href(items_for_site, rel="self")
        except ApiError as e:
            if e.return_code == 404:
                continue
            else:
                raise e

    return ""


def get_wall_time(duraction_adv, duration):
    import datetime
    import dateutil.parser
    if duraction_adv == "for":
        dt = (dateutil.parser.parse(duration) - dateutil.parser.parse("0h"))

    elif duraction_adv == "until":
        dt = (dateutil.parser.parse(duration) - datetime.datetime.now())

    return "%02d:%02d" % ((dt.seconds // 3600), (dt.seconds // 60) % 60)


try:

    if opts.command == "job":

        if opts.action == "list":

            print_site_item("jobs", opts.uid, opts.sites, opts.filter)

        elif opts.action == "add":
            wt = get_wall_time(opts.duration_adv, opts.duration)
            print(wt)
            exit(0)
            job_uid = g5k(s)("stable")("sites")(opts.site).post_job(node_count=opts.node_count,
                                                                    walltime=wt)
            print(job_uid)
            pass

        elif opts.action == "del":

            job_href = find_job(opts.uid, None if opts.site is None else [opts.site])
            g5k(s)(job_href).delete()
            logging.info("Job %s has been deleted " % job_href)
            exit(0)

    if opts.command == "dep":
        if opts.action == "add":
            job = g5k(s)(find_job(opts.uid, None if opts.site is None else [opts.site])).get_raw()

            if len(opts.nodes) == 0:
                node_list = job["assigned_nodes"]
            else:
                node_list = list(set(job["assigned_nodes"]) & set(opts.nodes))

            dep_uid = g5k(s)(get_link_href(job, "parent"))("deployments").post_provision(node_list=node_list,
                                                                                         key=settings_ssh_key,
                                                                                         environment=opts.environment)
            print(dep_uid)
            exit(0)

        if opts.action == "list":
            print_site_item("deployments", opts.uid, opts.sites, opts.filter)
            exit(0)




except KeyboardInterrupt:
    pass
