username: nherbaut
password: MY_PASSWORD
api-backend: https://api.grid5000.fr/
ssh_key_file_public: /home/nherbaut/.ssh/grenoble.pub
ssh_key_file_private: /home/nherbaut/.ssh/g5k
mailto: nicolas.herbaut@gmail.com
grid5k_ProxyCommand_domain_alias: g5k
environment: debian9-x64-base
default_site: grenoble